os: linux
dist: bionic

language: python
python: 
  - "3.6.1"
  - "3.7"
  - "3.8"

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - sourceline: 'deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /'
      key_url: 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub'
    packages:
    - cmake
    - llvm-11-dev
    - cuda-cudart-dev-10-1
    - cuda-core-10-1

before_install:
  - CUDA_HOME=/usr/local/cuda-10.1
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}

install:
  - pip install .