sudo: required
dist: bionic

language: python
python: 
  - "3.6.1"
  - "3.7"
  - "3.8"

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
      key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
    - cmake
    - llvm-11-dev

install:
  - pip install .