name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - 3.8
    steps:
      - name: Install CUDA
        run: sudo apt install -y nvidia-cuda-toolkit
      - name: Install LLVM-11
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
          repo-name: llvm
          keys-asc: https://apt.llvm.org/llvm-snapshot.gpg.key
          install: llvm-11-dev
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      - run: 'LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}'
      - run: 'PATH=${CUDA_HOME}/bin:${PATH}'
      - run: pip install lit filecheck
      - run: pip install .
      - run: llvm-mutate --version
      - run: lit -v llvm-mutate/tests
