name: Converted Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          #- 3.6.1
          #- 3.7
          - 3.8
    steps:
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'
      #- run: echo "Installed cuda version is: ${{ steps.cuda-toolkit.outputs.cuda }}"
      #- run: echo "Cuda install location: ${{ steps.cuda-toolkit.outputs.CUDA_PATH }}"
      - run: nvcc -V
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.1"
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.python-version }}'
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: 'LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}'
      - run: 'PATH=${CUDA_HOME}/bin:${PATH}'
      - run: pip install lit filecheck
      - run: pip install .
      - run: llvm-mutate --version
      - run: lit -v llvm-mutate/tests
